# Traefik Static Configuration
# https://doc.traefik.io/traefik/reference/static-configuration/file/

api:
  dashboard: true
  insecure: false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false
    network: app_net
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

accessLog:
  filePath: "/var/log/traefik/access.log"
  bufferingSize: 100

log:
  level: WARN
